
builds:
    - id: "cook-release"
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - arm
        - arm64
      dir: .
      main: ./cmd
      binary: cook