name: Release Cook Binary

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v `go list ./... | grep -v pkg`
  
    - name: TestBinary
      run: go test -v -run UB github.com/cozees/cook/tests/...

    - name: Release with GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
